version: "3.3"

services:
  db:
    container_name: monitadb
    image: mysql:5.7
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitadb
      MYSQL_USER: monita
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - monitanet

  monitaapi:
    container_name: monitaapi
    image: hellozee/monitaapi:v1
    hostname: monitaapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
    networks:
      - monitanet
    volumes:
      - .:/go/src/monita
    ports:
      - 8080:8080
    depends_on:
      - db

  mysqlexporter:
    container_name: mysqlexporter
    image: prom/mysqld-exporter
    hostname: mysqlexporter
    environment:
      DATA_SOURCE_NAME: "monita:pass@(db:3306)/"
      GET_HOSTS_FROM: dns
    ports:
      - 9104:9104
    networks:
      - monitanet
    depends_on:
      - db

  prometheus:
    container_name: prometheus_monita
    image: prom/prometheus
    hostname: prometheus
    environment:
      GET_HOSTS_FROM: dns
    ports:
      - 9090:9090
    networks:
      - monitanet
    depends_on:
      - mysqlexporter
      - monitaapi
    volumes:
      - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  monitanet:
    driver: bridge
