version: "3.3"

services:
  db:
    container_name: monitadb
    image: mysql:5.7
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitadb
      MYSQL_USER: monita
      MYSQL_PASSWORD: pass
    volumes:
      - ./resources/docker/mysql/init.sql:/docker-entrypoint-initdb.d/1.sql

    networks:
      - monitanet

  monitaapi:
    container_name: monitaapi
    image: hellozee/monitaapi:v1
    hostname: monitaapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
    networks:
      - monitanet
    volumes:
      - .:/go/src/monita
    ports:
      - 8080:8080
    depends_on:
      - db

  mysqlexporter:
    container_name: mysqlexporter
    image: prom/mysqld-exporter
    hostname: mysqlexporter
    environment:
      DATA_SOURCE_NAME: "monita:pass@(db:3306)/"
      GET_HOSTS_FROM: dns
    networks:
      - monitanet
    depends_on:
      - db

  prometheus:
    container_name: prometheus_monita
    image: prom/prometheus
    hostname: prometheus
    environment:
      GET_HOSTS_FROM: dns
    ports:
      - 9090:9090
    networks:
      - monitanet
    depends_on:
      - mysqlexporter
      - monitaapi
    volumes:
      - ./resources/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./resources/docker/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml

  prom_receiver:
    container_name: prom_receiver
    image: hellozee/prom-receiver
    hostname: promreceiver
    environment:
      GET_HOSTS_FROM: dns
    networks:
      - monitanet

  alertmanager:
    container_name: alertmanager_monita
    image: prom/alertmanager
    hostname: alertmanager
    environment:
      GET_HOSTS_FROM: dns
    ports:
      - 9093:9093
    volumes:
      - ./resources/docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitanet
    depends_on:
      - prometheus
      - prom_receiver

  grafana:
    container_name: grafana_monita
    image: grafana/grafana
    hostname: graphana
    ports:
      - 3000:3000
    networks:
      - monitanet

networks:
  monitanet:
    driver: bridge
