apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphana
  template:
    metadata:
      labels:
        app: graphana
    spec:
      containers:
        - name: graphana-container
          image: grafana/grafana
          ports:
            - containerPort: 3000
              name: http
